float64 id

float64 st
float64 vsa
float64 vwa

float64 gt
float64 gl
float64 go
float64 ga
float64 gh
float64 gp
float64 gr
float64 gs
float64 gk

float64 it
float64 iax
float64 iay
float64 iaz
float64 iny
float64 inr
float64 inp
float64 irr
float64 irp
float64 iry
float64 imgx
float64 imgy
float64 imgz

float64 vt
float64 vwo
float64 vs
float64 vchar
float64 vthr
float64 vbatt
float64 vrms
float64 vtempm
float64 vdir

