# Connection parameters
  /ethernet_comm/server_ip: "192.168.1.177"
  /ethernet_comm/server_port: 1511

# Communication parameters
  /ethernet_comm/message_size: 14
 
# Variable ranges
  /ethernet_comm/steer_us_range: [1240, 1740]      # Steer range in us
  /ethernet_comm/steer_rad_range: [-0.518, 0.469]  # Steer range in rad
  /ethernet_comm/speed_us_range: [1500, 1600]      # Speed range in us
  /ethernet_comm/speed_mps_range: [0.0, 1.43]      # Speed range in m/s

