#ifndef _SLROS_INITIALIZE_H_
#define _SLROS_INITIALIZE_H_

#include "slros_busmsg_conversion.h"
#include "slros_generic.h"

extern ros::NodeHandle * SLROSNodePtr;
extern const std::string SLROSNodeName;

// For Block state_estimator_opt_driftingcar_multibeta/Subscriber_To_Optitrack/Subscribe
extern SimulinkSubscriber<geometry_msgs::PoseStamped, SL_Bus_state_estimator_opt_drift_PoseStamped_8suobb> Sub_state_estimator_opt_driftingcar_multibeta_132;

// For Block state_estimator_opt_driftingcar_multibeta/Publisher/Publish1
extern SimulinkPublisher<std_msgs::Float64, SL_Bus_state_estimator_opt_drift_Float64_pfh567> Pub_state_estimator_opt_driftingcar_multibeta_170;

// For Block state_estimator_opt_driftingcar_multibeta/Publisher/Publish2
extern SimulinkPublisher<std_msgs::Float64, SL_Bus_state_estimator_opt_drift_Float64_pfh567> Pub_state_estimator_opt_driftingcar_multibeta_171;

// For Block state_estimator_opt_driftingcar_multibeta/Publisher/Publish3
extern SimulinkPublisher<std_msgs::Float64, SL_Bus_state_estimator_opt_drift_Float64_pfh567> Pub_state_estimator_opt_driftingcar_multibeta_172;

// For Block state_estimator_opt_driftingcar_multibeta/Publisher/Publish4
extern SimulinkPublisher<std_msgs::Float64, SL_Bus_state_estimator_opt_drift_Float64_pfh567> Pub_state_estimator_opt_driftingcar_multibeta_268;

// For Block state_estimator_opt_driftingcar_multibeta/Publisher/Publish5
extern SimulinkPublisher<std_msgs::Float64, SL_Bus_state_estimator_opt_drift_Float64_pfh567> Pub_state_estimator_opt_driftingcar_multibeta_318;

// For Block state_estimator_opt_driftingcar_multibeta/Publisher/Publish6
extern SimulinkPublisher<std_msgs::Float64, SL_Bus_state_estimator_opt_drift_Float64_pfh567> Pub_state_estimator_opt_driftingcar_multibeta_322;

// For Block state_estimator_opt_driftingcar_multibeta/Publisher/Publish7
extern SimulinkPublisher<std_msgs::Float64, SL_Bus_state_estimator_opt_drift_Float64_pfh567> Pub_state_estimator_opt_driftingcar_multibeta_326;

void slros_node_init(int argc, char** argv);

#endif
