# Simulator configuration parameters
  /single_track_sim/steering_actuator_model: 0      # Actuator model (0, ideal; 1, real)
  /single_track_sim/tyre_model: 1                   # Tyre model (0, linear; 1, fiala with saturation; 2, fiala without saturation)

  /single_track_sim/dt: 0.001                       # Integration step

# Vehicle parameters
  /single_track_sim/m: 1.9                          # Vehicle mass
  /single_track_sim/cog_a: 0.1368                   # Distance of COG from front axle
  /single_track_sim/cog_b: 0.1232                   # Distance of COG from rear axle
  /single_track_sim/mu: 0.385                       # Ground friction coefficient
  /single_track_sim/Cf: 50.13                       # Front cornering stiffness
  /single_track_sim/Cr: 122.05                      # Rear cornering stiffness
  /single_track_sim/Iz: 0.029                       # Yaw moment of inertia

# Steering actuator parameters
  /single_track_sim/mu_steer: 1.0                   # Transfer function gain
  /single_track_sim/wn_steer: 87.62                 # Transfer function crossover frequency
  /single_track_sim/csi_steer: 0.75                 # Transfer function damping
  /single_track_sim/tau_steer: 55                   # Transfer function delay (multiple of dt)

# Velocity actuator parameters
  /single_track_sim/mu_speed: 5.1282                # Transfer function gain

# Vehicle initial state
  /single_track_sim/r0: 0.0                         # Initial yaw rate
  /single_track_sim/Vy0: 0.0                        # Initial lateral velocity
  /single_track_sim/x0: 0.0                         # Initial position x
  /single_track_sim/y0: 0.0                         # Initial position y
  /single_track_sim/psi0: 0.0                       # Initial heading

# Measurements
  /single_track_sim/pose_decimation: 10             # Pose is published every decimation integration cycles
  /single_track_sim/imu_decimation: 10              # IMU is published every decimation integration cycles

