# Node parameters
  /drifting_controller/run_period: 0.01     # Node execution period [s]
  /drifting_controller/use_optitrack: true  # Use optitrack for sideslip estimation

# Controller parameters
  /drifting_controller/yawrate_equilibrium: 0.1     # Yaw rate at drifting equilibrium point
  /drifting_controller/beta_equilibrium: 0.1        # Beta at drifting equilibrium point
  /drifting_controller/steer_equilibrium: 0.1       # Steer at drifting equilibrium point
  /drifting_controller/speed_equilibrium: 0.1       # Speed at drifting equilibrium point
  /drifting_controller/yawrate_gain: 0.1            # Yaw rate gain (drifting controller)
  /drifting_controller/beta_gain: 0.1               # Beta gain (drifting controller)

