# Node parameters
  /AFI_controller/run_period: 0.01                  # Node execution period

# Vehicle parameters
  /AFI_controller/cog_dist_front: 0.1368            # Distance of COG from front axle
  /AFI_controller/cornering_front: 50.13            # Front cornering stiffness

# Controller parameters
  /AFI_controller/car2motor_velocity: 0.195         # Conversion factor from car speed in m/s to normalized motor speed ([-1,1])
  
  /AFI_controller/speed_thd: 0.05                   # Threshold to consider the absolute vehicle velocity equal to zero
  /AFI_controller/vel_filt_coeff: [0.0144, 0.0295, 0.0763, 0.0823, 0.0355, -0.0355, -0.0823, -0.0763, -0.0295, -0.0144]
                                                    # FIR velocity filter coefficients
  /AFI_controller/theta_offset: 0.0                 # Offset on optitrack theta angle

