# Node parameters
  /AGS_AFI_controller/run_period: 0.001                 # Node execution period

# Vehicle parameters
  /AGS_AFI_controller/cog_dist_front: 0.1368            # Distance of COG from front axle
  /AGS_AFI_controller/cornering_front: 50.13            # Front cornering stiffness

# Controller parameters
  /AGS_AFI_controller/matrix_filename: $(find ags_controller)/config/AGS_X0_HinfH2g_controller.mat

  /AGS_AFI_controller/car2motor_velocity: 0.195         # Conversion factor from car speed in m/s to normalized motor speed ([-1,1])
  
  /AGS_AFI_controller/speed_thd: 0.05                   # Threshold to consider the absolute vehicle velocity equal to zero
  /AGS_AFI_controller/vel_filt_coeff: [1, -1] #[0.0144, 0.0295, 0.0763, 0.0823, 0.0355, -0.0355, -0.0823, -0.0763, -0.0295, -0.0144]
                                                        # FIR velocity filter coefficients
  /AGS_AFI_controller/theta_offset: 0.0                 # Offset on optitrack theta angle

# Sideslip velocity estimator parameters
  /AGS_AFI_controller/vbeta_P: 0.1                      # Point P position for feedback linearization
  /AGS_AFI_controller/vbeta_Kpv: 1000.0                 # Proportional gain trajectory tracking controller
  /AGS_AFI_controller/vbeta_Ts: 0.0001                  # Sampling time

# Sideslip acceleration estimator parameters
  /AGS_AFI_controller/abeta_v_thd: 0.01                 # Velocity threshold for feedback linearization singularity
  /AGS_AFI_controller/abeta_Kpa: 1000.0                 # Proportional gain trajectory tracking controller
  /AGS_AFI_controller/abeta_Kda: 100.0                  # Derivative gain trajectory tracking controller
  /AGS_AFI_controller/abeta_Ta: 0.001                   # Derivative filter time constant trajectory tracking controller
  /AGS_AFI_controller/abeta_Ts: 0.0001                  # Sampling time

