# Simulator configuration parameters
  /single_track_sim/actuator_model: 0       # Actuator model (0, ideal; 1, real)
  /single_track_sim/tyre_model: 0           # Tyre model (0, linear; 1, fiala with saturation; 2, fiala without saturation)

  /single_track_sim/dt: 0.001               # Integration step

# Vehicle parameters
  /single_track_sim/m: 2.04                 # Vehicle mass
  /single_track_sim/cog_a: 0.1513           # Distance of COG from front axle
  /single_track_sim/cog_b: 0.1087           # Distance of COG from rear axle
  /single_track_sim/mu: 0.385               # Ground friction coefficient
  /single_track_sim/Cf: 25                  # Front cornering stiffness
  /single_track_sim/Cr: 50                  # Rear cornering stiffness
  /single_track_sim/Iz: 0.030               # Yaw moment of inertia

# Steering actuator parameters
  /single_track_sim/mu_steer: 1.0           # Transfer function gain
  /single_track_sim/wn_steer: 87.62         # Transfer function crossover frequency
  /single_track_sim/csi_steer: 0.75         # Transfer function damping
  /single_track_sim/tau_steer: 55           # Transfer function delay (multiple of dt)

# Vehicle initial state
  /single_track_sim/r0: 0.0                 # Initial yaw rate
  /single_track_sim/Vy0: 0.0                # Initial lateral velocity
  /single_track_sim/x0: 0.0                 # Initial position x
  /single_track_sim/y0: 0.0                 # Initial position y
  /single_track_sim/psi0: 0.0               # Initial heading
