# Port parameters
  /serial_comm/serial_port: "/dev/ttyACM1"
  /serial_comm/baudrate: 115200

# Communication parameters
  /serial_comm/timeout: 1                  # Timeout in milliseconds
  /serial_comm/message_size: 15
 
# Variable ranges
  /serial_comm/steer_us_range: [1000, 2000]      # steer range in us
  /serial_comm/steer_rad_range: [-1.989,1.657]  # steer range in rad, map for rubber tyres
#  /serial_comm/steer_rad_range: [-1, 1] #steer range in rad, for pwm map identification
  /serial_comm/steer_invert_command: true        # change the sign of the steer command
  /serial_comm/speed_us_range: [1000, 2000]       # Speed range in us
  /serial_comm/speed_mps_range: [-1.0, 1.0]   # Speed range in m/s

