# Port parameters
  /serial_comm/serial_port: "/dev/ttyACM1"
  /serial_comm/baudrate: 115200

# Communication parameters
  /serial_comm/timeout: 1                  # Timeout in milliseconds
  /serial_comm/message_size: 15
 
# Variable ranges
  /serial_comm/steer_us_range: [1000, 2000]      #steer range in us
  /serial_comm/steer_rad_range: [1.577, -1.423]  #steer range in rad
  /serial_comm/speed_us_range: [950, 2010]       # Speed range in us
  /serial_comm/speed_mps_range: [-1.0, 1.0256]   # Speed range in m/s

