# Accelerometer calibration
  /myahrs_driver/acc_rpy: [0.0, 0.0, 0.0]
  /myahrs_driver/acc_bias: [0.0, 0.0, 0.0]

# Gyroscope calibration
  /myahrs_driver/gyro_rpy: [0.0, 0.0, 0.0]
  /myahrs_driver/gyro_bias: [0.0, 0.0, 0.0]

