# Beta estimator velocity configuration parameters
  /beta_estimator_velocity_driftingcar/p: 0.10              # [m] distance of the feedback linearization point from the vehicle COG
  /beta_estimator_velocity_driftingcar/Kp: 100.0 # [rad/s] crossover freq
