# Feedback linearization configuration parameters
  /test_feedback_linearization/run_period: 0.01          # Node execution period

  /test_feedback_linearization/cog_dist_front: 0.70      # Distance of cog from front
  /test_feedback_linearization/cog_dist_rear: 1.42       # Distance of cog from rear
 
  /test_feedback_linearization/P_dist: 1.0               # Distance of point P for feedback linearization
  /test_feedback_linearization/speed_thd: 0.05           # Threshold to consider the absolute vehicle velocity equal to zero
  /test_feedback_linearization/vel_filt_coeff: [0.0144, 0.0295, 0.0763, 0.0823, 0.0355, -0.0355, -0.0823, -0.0763, -0.0295, -0.0144]
                                                         # FIR velocity filter coefficients
  
  /test_feedback_linearization/Kp: 1.0                   # Position loop proportional gain
  /test_feedback_linearization/Ti: 0.0                   # Position loop integral time
  /test_feedback_linearization/vp_min: -10.0             # Position loop low saturation
  /test_feedback_linearization/vp_max:  10.0             # Position loop up saturation

  /test_feedback_linearization/radius: 1.0               # Radius for circle and squircle trajectories
  /test_feedback_linearization/xcenter: -0.32            # Center coordinate x for circle and squircle trajectories
  /test_feedback_linearization/ycenter: 1.20             # Center coordinate y for circle and squircle trajectories
  /test_feedback_linearization/omega: 0.5                # Rotational velocity for circle and squircle trajectories
  /test_feedback_linearization/const_speed: 0.7          # Constant velocity for step sequence
